print('sandbox:hello word')
-- Trigger.addHandler(this:cfg(), "ENTITY_ENTER", function(context)
--     local entity = context.obj1
--     --local from = context.obj2
--     --if from then
--         entity:startAI()
--         local control = entity:getAIControl()
--         control:setAiData("homeSize", 50)
--         control:setAiData("enableNavigate", true)
--         entity:setAITargetPos(Vector3.new(4, 1, 16),true)
--         print('Debug')
--     --end
-- end)