print("startup ui")
-------------------UI-Btn_sevenLogin----------------
local Btn_sevenLogin = self:child("Btn_sevenLogin")
local Img_redDot = Btn_sevenLogin:child("EffectWindow")
local Cover = Btn_sevenLogin:child("Cover")
local EffectWindowPoint = Btn_sevenLogin:child("EffectWindowPoint")
---------------------UI-Login--------------------------------
local bg = self:child("bg")
local Btn_signIn = bg:child("Btn_signIn")
local Btn_close = bg:child("Btn_close")
local EffectPoints1 = bg:child("EffectPoints1")
local Wnd_dayData1 = bg:child("Img_selectIcon1")
local Img_haveGotIcon1 = bg:child("Img_haveGotIcon1")
local Wnd_dayData2 = bg:child("Img_selectIcon2")
local Img_haveGotIcon2 = bg:child("Img_haveGotIcon2")
local Wnd_dayData3 = bg:child("Img_selectIcon3")
local Img_haveGotIcon3 = bg:child("Img_haveGotIcon3")
local Wnd_dayData4 = bg:child("Img_selectIcon4")
local Img_haveGotIcon4 = bg:child("Img_haveGotIcon4")
local Wnd_dayData5 = bg:child("Img_selectIcon5")
local Img_haveGotIcon5 = bg:child("Img_haveGotIcon5")
local Wnd_dayData6 = bg:child("Img_selectIcon6")
local Img_haveGotIcon6 = bg:child("Img_haveGotIcon6")
local Wnd_dayData7 = bg:child("Img_selectIcon7")
local Img_haveGotIcon7 = bg:child("Img_haveGotIcon7")
---------------------------------------------
PackageHandlers.registerClientHandler("Tutorial Updated", function(player, pack)
    print("UpdateSvlogin")
    print(Lib.pv(pack))
    local hour = tonumber(os.date("%H"))
	local minute = tonumber(os.date("%M"))
	local second = tonumber(os.date("%S"))
	local dayEndTime = (24 - hour - 1) * 60 * 60 * 20 + (60 - minute - 1) * 60 * 20 + (60 - second) * 20
	if pack.Day < dayEndTime  then
        Img_redDot:setVisible(true)
        EffectWindowPoint:setVisible(true)
    else 
        Btn_signIn:setProperty("Disabled", "true")
    end
    if  pack.Count == 7  then 
        Btn_signIn:setProperty("Disabled", "true")
        Wnd_dayData7:setVisible(true)
        Img_haveGotIcon7:setVisible(true)
        Wnd_dayData6:setVisible(true)
        Img_haveGotIcon6:setVisible(true)
        Wnd_dayData5:setVisible(true)
        Img_haveGotIcon5:setVisible(true)
        Wnd_dayData4:setVisible(true)
        Img_haveGotIcon4:setVisible(true)
        Wnd_dayData3:setVisible(true)
        Img_haveGotIcon3:setVisible(true)
        Wnd_dayData2:setVisible(true)
        Img_haveGotIcon2:setVisible(true)
        Wnd_dayData1:setVisible(true)
        Img_haveGotIcon1:setVisible(true)
    elseif pack.Count == 6  then 
        Wnd_dayData6:setVisible(true)
        Img_haveGotIcon6:setVisible(true)
        Wnd_dayData5:setVisible(true)
        Img_haveGotIcon5:setVisible(true)
        Wnd_dayData4:setVisible(true)
        Img_haveGotIcon4:setVisible(true)
        Wnd_dayData3:setVisible(true)
        Img_haveGotIcon3:setVisible(true)
        Wnd_dayData2:setVisible(true)
        Img_haveGotIcon2:setVisible(true)
        Wnd_dayData1:setVisible(true)
        Img_haveGotIcon1:setVisible(true)
    elseif pack.Count == 5  then
        Wnd_dayData5:setVisible(true)
        Img_haveGotIcon5:setVisible(true)
        Wnd_dayData4:setVisible(true)
        Img_haveGotIcon4:setVisible(true)
        Wnd_dayData3:setVisible(true)
        Img_haveGotIcon3:setVisible(true)
        Wnd_dayData2:setVisible(true)
        Img_haveGotIcon2:setVisible(true)
        Wnd_dayData1:setVisible(true)  
        Img_haveGotIcon1:setVisible(true)
    elseif pack.Count == 4  then  
        Wnd_dayData4:setVisible(true)
        Img_haveGotIcon4:setVisible(true)
        Wnd_dayData3:setVisible(true)
        Img_haveGotIcon3:setVisible(true)
        Wnd_dayData2:setVisible(true)
        Img_haveGotIcon2:setVisible(true)
        Wnd_dayData1:setVisible(true)
        Img_haveGotIcon1:setVisible(true) 
    elseif pack.Count == 3  then  
        Wnd_dayData3:setVisible(true)
        Img_haveGotIcon3:setVisible(true)
        Wnd_dayData2:setVisible(true)
        Img_haveGotIcon2:setVisible(true)
        Wnd_dayData1:setVisible(true)
        Img_haveGotIcon1:setVisible(true)
    elseif pack.Count == 2  then  
        Wnd_dayData2:setVisible(true)
        Img_haveGotIcon2:setVisible(true)
        Wnd_dayData1:setVisible(true)
        Img_haveGotIcon1:setVisible(true)
    elseif pack.Count == 1  then  
        Wnd_dayData1:setVisible(true)
        Img_haveGotIcon1:setVisible(true)
    -- elseif pack.Count == 0  then  
        -- EffectWindowPoint:setVisible(true)
    end
end)
Btn_sevenLogin.onMouseClick = function()
    bg:setVisible(true)
end
Btn_signIn.onMouseClick = function()
    Btn_signIn:setProperty("Disabled", "true")
    bg:setVisible(false)
    EffectWindowPoint:setVisible(false)
    Wnd_dayData1:setVisible(false)
    Img_haveGotIcon1:setVisible(true)
    Img_redDot:setVisible(false)
    PackageHandlers.sendClientHandler("Check7day")
    PackageHandlers.sendClientHandler("Step1")
end
Btn_close.onMouseClick = function()
   bg:setVisible(false)
end
